openapi: "3.0.0"
info:
  title: Food App API
  version: 1.0.0
  description: RESTful API for managing food items and categories
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /foods:
    get:
      summary: Get list of foods
      responses:
        '200':
          description: A list of foods
    post:
      summary: Create a new food
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Food'
      responses:
        '201':
          description: Food created
components:
  schemas:
    Food:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: double
    # Add more schemas for other entities (e.g., FoodCategory)
